# Project variables

variable project_name {
    type =string
    default = "Expence"
}

variable environment {
    type =string
    default = "Dev"
}

variable comman_tags {
    type = map
    default ={}
}
##############  VPC  ##########
variable vpc_cidr {
    type = string
    default = "10.0.0.0/16"
}

variable enable_host_names {
    type = bool
    default=true
}

# IGW tags
variable gw {
    type = map
    default = {}
}
## Public subnet tags
variable public_subnet_cidr_tags {
    type = map
    default = {}
}

variable public_subnet_cidrs {
    type = list
    validation {
        condition = length(var.public_subnet_cidrs) == 2
        error_message = "You must provide exactly two CIDRs for public subnets."
    }
}

# # Private subnet variables
variable private_subnet_cidrs_tags {
    type = map
    default = {}
}

variable private_subnet_cidrs {
    type = list
    validation {
        condition = length(var.private_subnet_cidrs) == 2
        error_message = "You must provide exactly two CIDRs for private subnets."
    }
}

# # Database variables
variable database_subnet_cidr_tags {
    type = map
    default = {}
}

variable "database_subnet_cidrs" {
    type = list
    validation {
        condition = length(var.database_subnet_cidrs) == 2
        error_message = "You must provide exactly two CIDRs for database subnets."
    } 
}

variable "database_subnet_group_cidr_tags" {
    type = map
    default = {}
}

variable "nat_gateway_tags" {
    type = map
    default = {}
}
# # Route Table variables
variable "route_table_public_tags" {
    type = map
    default = {}
}

variable "route_table_database_tags" {
    type = map
    default = {}
}

variable "route_table_private_tags" {
    type = map
    default = {}
}
variable "instance_type" {
    type = string
    description = "EC2 instance type for the VPC"
    default = "t3.micro"
}

variable "generated_key_name" {
  type        = string
  default     = "terraform-key-pair"
  description = "Key-pair generated by Terraform"
}
